In [2]:
# kasus ML jika data ada yang berupa teks(dengan cara one hot encoder)

# One Hot Encoder

In [5]:
import numpy as np 
import pandas as pd 

## 1. read dataset (data.csv)

In [8]:
data = pd.read_csv('ml10.csv')
data

luas  harga     kota
0   1000   1000    depok
1   2000   2000    depok
2   3000   3000    depok
3   3000   3000    depok
4   4000   4000    depok
5   5000   5000    depok
6   1000    500    bogor
7   2000   1000    bogor
8   3000   1500    bogor
9   4000   2000    bogor
10  5000   2500    bogor
11  1000   2000  jakarta
12  2000   4000  jakarta
13  3000   6000  jakarta
14  4000   8000  jakarta
15  5000  10000  jakarta

### 2. labeling -Sklearn Label Encoder

In [10]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
dataLabel = data
dataLabel['kota'] = label.fit_transform(dataLabel['kota'])
dataLabel

luas  harga  kota
0   1000   1000     1
1   2000   2000     1
2   3000   3000     1
3   3000   3000     1
4   4000   4000     1
5   5000   5000     1
6   1000    500     0
7   2000   1000     0
8   3000   1500     0
9   4000   2000     0
10  5000   2500     0
11  1000   2000     2
12  2000   4000     2
13  3000   6000     2
14  4000   8000     2
15  5000  10000     2

In [27]:
x = dataLabel[['luas','kota']].values
y = dataLabel['harga']
x

array([[1000,    1],
       [2000,    1],
       [3000,    1],
       [3000,    1],
       [4000,    1],
       [5000,    1],
       [1000,    0],
       [2000,    0],
       [3000,    0],
       [4000,    0],
       [5000,    0],
       [1000,    2],
       [2000,    2],
       [3000,    2],
       [4000,    2],
       [5000,    2]], dtype=int64)

### 3. one hot encoder

In [28]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# col trans
coltrans = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],
    remainder = 'passthrough'
)

x = np.array(coltrans.fit_transform(x), dtype = np.int64)
x

array([[   0,    1,    0, 1000],
       [   0,    1,    0, 2000],
       [   0,    1,    0, 3000],
       [   0,    1,    0, 3000],
       [   0,    1,    0, 4000],
       [   0,    1,    0, 5000],
       [   1,    0,    0, 1000],
       [   1,    0,    0, 2000],
       [   1,    0,    0, 3000],
       [   1,    0,    0, 4000],
       [   1,    0,    0, 5000],
       [   0,    0,    1, 1000],
       [   0,    0,    1, 2000],
       [   0,    0,    1, 3000],
       [   0,    0,    1, 4000],
       [   0,    0,    1, 5000]], dtype=int64)

### 4. linear regression

In [31]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

### 5. prediction

In [32]:
#Harga di depok dengan luas tanah 1000
model.predict([[0, 1, 0, 1000]])

array([666.6666667])